version: '3'
services: 
  db:
    image: mysql:latest
    container_name: mysql-wordpress-morska
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - wordpress-networks
    volumes:
      - db-data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: worpress-api-morska
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 8001:80
    env_file:
      - .env
    networks:
      - wordpress-networks
    volumes:
      - wordpress-data:/var/www/html
networks:
  wordpress-networks:
    driver: bridge
volumes:
  db-data:
  wordpress-data: